### ISSUE TITLE
Calculation of distance between two points fails on Redhat

### ISSUE THREAD

**Issue by glampr** [rgeo/rgeo#92] opened 2015-04-08 22:36 UTC
Running the following on my production server which is a Redhat 6 machine gives the following error:

``` ruby
2.1.1 :001 > a = RGeo::Geographic.simple_mercator_factory.point(0, 0)
 => #<RGeo::Geographic::ProjectedPointImpl:0x3c920b8 "POINT (0.0 0.0)"> 
2.1.1 :002 > b = RGeo::Geographic.simple_mercator_factory.point(1, 1)
 => #<RGeo::Geographic::ProjectedPointImpl:0x3c4d580 "POINT (1.0 1.0)"> 
2.1.1 :003 > a.distance(b)
ruby: GeometryComponentFilter.cpp:35:
virtual void geos::geom::GeometryComponentFilter::filter_ro(const geos::geom::Geometry*):
Assertion `0' failed.
```

and the console crashes and exits.
The code above works without a problem on my OSX development machines.

**Comment by gavit** [comment] 2015-12-23 09:54
Same issue on CentOS release 6.6 (Final). geos 3.4.2-1.rhel6, gcc 4.4.7-16.el6, proj 4.8.0-2.rhel6. Probably a duplicate of [#535](https://trac.osgeo.org/geos/ticket/535)

**Comment by rohan-deshpande** [comment] 2016-04-13 03:10
I am also having this issue on RHEL 6.7, is there actually a fix at all? This basically makes geos unusable and breaks everything. Does upgrading the version help? I couldn't gather if there was a solution in https://trac.osgeo.org/geos/ticket/535

**Comment by gavit** [comment] 2016-04-13 11:19
Does compiling from source affect the packaging system?
I was hoping a new package was downloadable /installable :(

**Comment by rohan-deshpande** [comment] 2016-04-13 21:04
I'm not sure ... compiling from the source was the only thing available to me on the stack I'm on. This solution did fix the problem though. You'd think it would be in the documentation somewhere, but it's not.

**Comment by AvlWx2014** [comment] 2017-05-22 13:20
@rohan-deshpande can you tell me what the --enable-php flag does? Is that a necessary addition or is the -m64 option most important?

**Comment by wlmcewen** [comment] 2017-08-21 21:00
Sharing here, as I am running into the same issue and intend to this relatively painless workaround to my particular problem by finding the length of a line instead:

    2.2.4p230 :008 > point1 = factory.point(-96.829843,  42.856822)
     => #<RGeo::Geographic::ProjectedPointImpl:0x42218e4 "POINT (-96.829843 42.856822)"> 
    2.2.4p230 :009 > point2 = factory.point(-96.829843,  46.856822)
     => #<RGeo::Geographic::ProjectedPointImpl:0x42236e4 "POINT (-96.829843 46.856822)"> 
    2.2.4p230 :010 > line = factory.line(point1,point2)
     => #<RGeo::Geographic::ProjectedLineImpl:0x4237d10 "LINESTRING (-96.829843 42.856822, -96.829843 46.856822)"> 
    2.2.4p230 :011 > line.length
     => 628530.9865136826 
    2.2.4p230 :012 > point1.distance(point2)
    script/rails: GeometryComponentFilter.cpp:35: virtual void geos::geom::GeometryComponentFilter::filter_ro(const geos::geom::Geometry*): Assertion `0' failed.
    Aborted

Seems to do the trick!

**Comment by keithdoggett** [comment] 2020-10-09 03:16
Closing this since the related libgeos issue was closed (upstream compiler error).

**Closed by keithdoggett** 2020-10-09 03:16 UTC
