### ISSUE TITLE
Union giving nil or Empty collection

### ISSUE THREAD

**Issue by nikolai-b** [rgeo/rgeo#189] opened 2018-05-14 19:01 UTC
Hi,
I'm getting a similar issue to #104

```ruby
geom = RGeo::Geos.factory(srid: 4326).parse_wkt("
GEOMETRYCOLLECTION (
  POLYGON ((-3.788091732031289 55.28171639104471, -3.282720638281247 55.01017018336803, -4.351141048437512 54.8476193969965, -3.788091732031289 55.28171639104471)), 
  POLYGON ((-4.11245981848872 55.305395022157526, -3.5630216447403713 54.90747510684706, -5.182749306205093 54.91177262081619, -4.11245981848872 55.305395022157526))
)")
geom.buffer(0.001).union(geom)
```
gives
```ruby
=> #<RGeo::Geos::CAPIGeometryCollectionImpl:0x2afb8e317db0 "GEOMETRYCOLLECTION EMPTY">
```

I also get a similar issue with 
```ruby
geom = RGeo::Geos.factory(srid: 4326).parse_wkt("
POLYGON ((
  0.12258630664064392 52.215823843772895, 
  0.29579263598633143 52.30439790611968, 
  0.1074801054687581 52.16267870598888, 
  0.10593515307618633 52.21603419328302, 
  0.1057634916992389 52.215718668644016, 
  0.12258630664064392 52.215823843772895
))"
geom.buffer(0.001).union(geom)
```

This time returns `nil` but this seems a bit more acceptable as in this case there is a `Self-intersection[0.10594425662997 52.2157197987744 0]` in the Polygon whereas the GeometryCollection appears to be valid.  Any ideas?

```SQL
SELECT PostGIS_full_version();
=> "postgis_full_version"=>"POSTGIS="2.3.1 r15264" GEOS="3.5.1-CAPI-1.9.1 r4246" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.1.2, released 2016/10/24" LIBXML="2.9.4" LIBJSON="0.12.1" RASTER"
```

Would you like me to add this as a failing test?

**Comment by keithdoggett** [comment] 2020-09-04 19:36
I tried the first example using libgeos and postgis, and in both cases, `POLYGON EMPTY` was returned. I'm going to close the issue since it seems like this doesn't really deviate from the expected behavior.

I know this is old, but if it's still relevant, you can re-open and provide the expected behavior.

**Closed by keithdoggett** 2020-09-04 19:36 UTC
