### ISSUE TITLE
Invalid Geometry.

### ISSUE THREAD

**Issue by Ume1931** [rgeo/rgeo#188] opened 2018-04-11 12:27 UTC
I am trying to save a a shapefile in database which has intersecting lines.
But whenever i try to get geometry i get nil in response. I have even attached the file below.
Shouldn't the latest version of geos(1.0.0) remove duplicate points & resolve this issue?

[Archive.zip](https://github.com/rgeo/rgeo/files/1898742/Archive.zip)

**Comment by Ume1931** [comment] 2018-04-11 13:10
Just read this in limitations of Rgeo:
"The ESRI polygon specification allows interior rings to touch their exterior ring in a finite number of points. This technically violates the OGC Polygon definition. However, such a structure remains a legal OGC MultiPolygon, and it is in principle possible to detect this case and transform the geometry type accordingly. We do not yet do this. Therefore, it is possible for a shapefile with polygon type to yield an illegal geometry."

How can i achieve that?

**Comment by pedros007** [comment] 2018-04-11 18:45
If RGeo could represent the geometry (rather than return `nil`), you could try `the_geom.buffer(0)`.  This is one way to make valid geometries in Postgis.  Details on `ST_MakeValid` vs `ST_Buffer(the_geom, 0)` can be found at [Repairing Invalidity](http://workshops.boundlessgeo.com/postgis-intro/validity.html#repairing-invalidity).  However, the Shapefile & GeoJSON parsers return nil for invalid geometries, afaik.

One workaround I've done in the past is to use `ogr2ogr` which ships with [GDAL](http://www.gdal.org/) to insert invalid geometries to Postgis then use Postgis to validate the geometry.  Something like this:

```sh
ogr2ogr -nln my_table -lco GEOMETRY_NAME=geom -f PostgreSQL PG:dbname=warmerda abc.shp
```
```sql
UPDPATE my_table SET geom=ST_MakeValid(geom) WHERE ST_IsValid(geom) = false
```

Find more `ogr2ogr` Postgres options in the [PostgreSQL driver](http://www.gdal.org/drv_pg.html) and/or [PGDump driver](http://www.gdal.org/drv_pgdump.html) docs.

**Comment by keithdoggett** [comment] 2020-09-23 12:49
I'm going to close this since the nil resposne is not a bug and there's good discussion about how to resolve validity issues.

**Closed by keithdoggett** 2020-09-23 12:49 UTC
